import { SHOPIFY_ADMIN_API_URL, SHOPIFY_AUTH_API_URL } from "@env";

// Specific endpoint URLs
export const API_ENDPOINTS = {
  COLLECTION_LIST: `${SHOPIFY_ADMIN_API_URL}`,
  COLLECTION_PRODUCTS_LIST: `${SHOPIFY_ADMIN_API_URL}`,
  PRODUCT_DETAILS: `${SHOPIFY_ADMIN_API_URL}`,
  LOGIN: `${SHOPIFY_AUTH_API_URL}`,
  REGISTER: `${SHOPIFY_AUTH_API_URL}`,
  FORGOT_PASSWORD: `${SHOPIFY_AUTH_API_URL}`,
  FETCH_CART: `${SHOPIFY_AUTH_API_URL}`,
  UPDATE_CART: `${SHOPIFY_AUTH_API_URL}`,
  CREATE_CART: `${SHOPIFY_AUTH_API_URL}`,
  REMOVE_CART: `${SHOPIFY_AUTH_API_URL}`,
  ADD_TO_CART: `${SHOPIFY_AUTH_API_URL}`,
  ADD_CUSTOMER_ADDRESS: `${SHOPIFY_AUTH_API_URL}`,
  RECOMMENDED_PRODUCTS: `${SHOPIFY_AUTH_API_URL}`,
  SEARCH_PRODUCTS: `${SHOPIFY_AUTH_API_URL}`,
  SHOP_POLICIES: `${SHOPIFY_AUTH_API_URL}`,
};
